name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Debug build output
        run: ls -la dist && ls -la dist/assets || true
      - name: Copy public images to dist
        run: |
          mkdir -p dist/assets
          mkdir -p dist/images
          cp -r public/assets/* dist/assets/ || true
          cp -r public/images/* dist/images/ || true
          echo "Contents of dist directory after copy:"
          ls -la dist
          echo "Contents of dist/assets directory:"
          ls -la dist/assets || true
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Create .nojekyll file
        run: touch dist/.nojekyll
      - name: Create 404.html for SPA routing
        run: cp dist/index.html dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
